#!/usr/bin/env python3
"""Generate native tool-adapter artifacts from the canonical project-os playbooks.

Single source of truth stays in tools/skills/*/SKILL.md and tools/instructions/*.md;
this script derives, deterministically:

  .claude/skills/<name>/SKILL.md   Claude Code native skills (auto-discovered, /name invocable)
  .claude/agents/planner.md                Claude Code subagent for LIFECYCLE.md preflight (model-pinned)
  .claude/agents/independent-reviewer.md   Claude Code subagent for QUALITY.md independent review (model-pinned)
  .cursor/rules/*.mdc              Cursor rules (instructions inlined per the cursor adapter mapping)

With --install-hooks it also installs the Claude Code hook set into .claude/settings.json
(copy when absent, merge the missing "hooks" key when present, leave any existing hooks alone).
With --check it writes nothing and exits 1 if any generated file is stale (for CI/pre-commit).

Stdlib only. Re-run after changing skills or instructions (see tools/skills/adapter-sync/SKILL.md).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

GENERATED_NOTE = "<!-- generated by tools/scripts/generate-adapters.py from %s; edit the source and re-run, do not edit this file -->"

# instruction file -> (rule name, globs, always-apply)
CURSOR_RULES = [
    ("LIFECYCLE.md", "lifecycle", ["**/*"]),
    ("STATUSES.md", "statuses", ["**/*"]),
    ("QUALITY.md", "quality", ["**/*"]),
    ("SNAPSHOT.md", "snapshot", ["SNAPSHOT.yaml"]),
    ("TRACEABILITY.md", "traceability", ["docs/**/*.md"]),
    ("OBSIDIAN.md", "obsidian", ["docs/**/*.md"]),
    ("MARKDOWN.md", "markdown", ["**/*.md"]),
]

# Model pins for the two subagents (HC-008 delegation hint). The lifecycle
# phases that most reward capability — planning and adversarial review — get
# the pin. Full model IDs, not aliases, so `reviewed_by` stays deterministic
# across releases. The pins are revisited at each model release; they are not a
# standing claim about the strongest model available.
#
# Both are Fable 5.1 as of 2026-09-03 (project-os-dev ISS-0044), and
# deliberately the same as the likely authoring model. The pins used to differ as a proxy for independence; that
# proxy is retired. Independence is now a clean context and a separate session
# (QUALITY.md, "Independent review (clean-context)"), which subagents provide by
# construction — they start from the notes and the diff, never the author's
# reasoning trace.
#
# The change is evidence-backed. Tested against the one case in the fleet with a
# known answer, a clean-context session of the SAME model as the author caught
# the defect the old family rule predicted only a different family could catch,
# rated it the run's only high-severity finding, and described it more
# accurately than the different-pin reviewer had. See project-os-dev ADR-0013
# and TASK-0077.
#
# `reviewed_by` still records the model. That is provenance, not a compliance
# token: a later reader needs to know who reviewed, and a future finding about a
# specific model's blind spots needs the data.
PLANNER_MODEL = "claude-fable-5-1"
REVIEWER_MODEL = "claude-fable-5-1"

PLANNER_AGENT = """---
name: planner
description: project-os preflight — classify the prompt, allocate IDs, update SNAPSHOT.yaml and create the notes before any code is written. Use PROACTIVELY whenever a prompt implies work (bugfix, feature, refactor, behavior change) that has no snapshot item yet, and for scoping or re-planning questions.
model: %s
---

You are the project-os planning agent. You own preflight (`tools/instructions/LIFECYCLE.md`, "Preflight (must happen before code changes)") and nothing else.

1. Follow the canonical playbooks rather than improvising: `tools/skills/issue-intake/SKILL.md` (including its spec-ambiguity check before any ID is allocated), `tools/skills/feature-scaffold/SKILL.md`, `tools/skills/task-breakdown/SKILL.md`, `tools/skills/impact-analysis/SKILL.md`, and `tools/skills/backlog-grooming/SKILL.md` when the prompt is about ordering rather than new work.
2. Update `SNAPSHOT.yaml` first (create `items.*` entries with relationships and set `focus`; IDs and counters follow `tools/instructions/LIFECYCLE.md`, "Mandatory Automated Documentation"), then create the notes from `docs/__templates__/` with frontmatter consistent with the snapshot.
3. Respect phase boundaries (`docs/PHASES.md`): flag future-phase dependencies instead of quietly planning around them.
4. Do not write or edit implementation code. Planning artifacts only — the main loop implements what you plan.
5. If part of the request is ambiguous, allocate and draft what is settled, and return the ambiguities as questions beside it; which reading to build is the user's decision (`tools/instructions/LIFECYCLE.md`, "When to pause for the user"). The threshold is `tools/skills/issue-intake/SKILL.md` step 1.
6. Expect the delegation to carry the user's prompt verbatim and one sentence on what the result enables; if either is missing, ask for it in your first line rather than classifying a paraphrase. Where the verbatim text lands is `tools/skills/issue-intake/SKILL.md` step 6.

Return the allocated IDs with their paths, a short plan summary per item, any impact-analysis conflicts, and open questions.
""" % PLANNER_MODEL

REVIEWER_AGENT = """---
name: independent-reviewer
description: Independent review pass at the gates project-os QUALITY.md states (a TST-* reaching passing, a requirement reaching implemented, a feature reaching done). Reviews adversarially from a clean context and records reviewed_by/review_date/review_verdict in the note frontmatter.
model: %(model)s
---

You are the project-os independent reviewer. Your review counts only if you genuinely try to refute the work, not confirm it.

1. Read `tools/skills/independent-review/SKILL.md` in full and follow it exactly.
2. Read the notes under review (TST-*/REQ-*/FEAT-*, and a CHG-* only when asked; a change note owes no review) and the code or docs they claim to cover; attempt to refute each claim (does the test fail when the fix is broken? does the change note match what actually changed?).
3. Record the outcome in each reviewed note's frontmatter: `reviewed_by: model:%(model)s`, `review_date: <today>`, `review_verdict: approved` or `changes-requested` (with your findings in the note body).
4. What makes this pass independent is stated once in `tools/instructions/QUALITY.md`, "Independent review (clean-context)": your context, not your model. Protect it. Do not ask the author what they meant, and do not reconstruct their intent charitably; if the change cannot be justified from the notes alone, that is a finding about the documentation, which is the point of the handoff surface.
5. You are very likely the same model that wrote the work. That is expected and is not a defect in this pass; a shared model correlates *capability*, a shared context correlates *commitment*, and it is the second that review exists to break. What you must not be is the same *session*: if you find yourself with any memory of authoring this, stop and say so — that is self-review and your verdict cannot settle it.
6. State plainly in your report what was independent (fresh context, separate session) and what was not (same model family, recorded in `reviewed_by`). A reader should be able to judge the independence rather than infer it.
""" % {"model": REVIEWER_MODEL}


def fail(msg):
    print("generate-adapters: %s" % msg, file=sys.stderr)
    return 2


def parse_frontmatter_body(text):
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if m:
        return m.group(1), m.group(2)
    return "", text


def skill_title(body, fallback):
    m = re.search(r"^#\s+Skill:\s*(.+)$", body, re.MULTILINE)
    if m:
        return m.group(1).strip()
    m = re.search(r"^#\s+(.+)$", body, re.MULTILINE)
    return m.group(1).strip() if m else fallback


def when_to_use(body):
    m = re.search(r"^##\s+When to use\s*\n(.*?)(?=^##\s|\Z)", body, re.MULTILINE | re.DOTALL)
    if not m:
        return []
    bullets = re.findall(r"^-\s+(.+)$", m.group(1), re.MULTILINE)
    return [re.sub(r"\s+", " ", b).strip().rstrip(".") for b in bullets]


def build_skill(name, src_rel, body):
    title = skill_title(body, name)
    bullets = when_to_use(body)
    desc = "project-os %s playbook" % title.lower()
    if bullets:
        desc += ". Use when: " + "; ".join(bullets)
    desc = re.sub(r"[`\[\]]", "", desc)
    if len(desc) > 400:
        desc = desc[:397].rstrip() + "..."
    lines = [
        "---",
        "name: %s" % name,
        "description: %s" % json.dumps(desc),
        "---",
        "",
        GENERATED_NOTE % src_rel,
        "",
        "This operation is governed by the canonical project-os playbook.",
        "",
        "1. Read `%s` in full; it is the source of truth for this skill." % src_rel,
        "2. Follow its checklist, honouring the preflight and close-out rules in `tools/instructions/LIFECYCLE.md` (document first; update `SNAPSHOT.yaml` and the notes in the same turn as the work). Where the checklist and the repo disagree, say so and file an `ISS-*` rather than improvising.",
    ]
    if bullets:
        lines += ["", "Use when:", ""] + ["- %s." % b for b in bullets]
    # The three close-out steps belong to the close-out playbook. Repeating them
    # in every generated skill told inbox-triage and ad-hoc-intake, which push
    # nothing, to confirm a CI run (project-os-dev TASK-0101).
    if name == "close-out":
        lines += [
            "",
            "3. Then follow `tools/instructions/LIFECYCLE.md` close-out steps 7 to 9: run the validator, run `--as-committed` before pushing, and confirm the CI run went green.",
        ]
    lines.append("")
    return "\n".join(lines)


def build_cursor_rule(name, globs, src_rel, text):
    _fm, body = parse_frontmatter_body(text)
    body = body.strip()
    first_para = ""
    for para in re.split(r"\n\s*\n", re.sub(r"^#.*$", "", body, flags=re.MULTILINE).strip()):
        p = re.sub(r"\s+", " ", para).strip()
        if p:
            first_para = p
            break
    desc = re.sub(r"[`\[\]]", "", first_para)[:200] or ("project-os %s rules" % name)
    lines = [
        "---",
        "description: %s" % json.dumps(desc),
        "globs: %s" % json.dumps(globs),
        "---",
        "",
        GENERATED_NOTE % src_rel,
        "",
        body,
        "",
    ]
    return "\n".join(lines)


def generate(root):
    """Return {repo-relative path: content} for every generated artifact."""
    out = {}
    skills_dir = root / "tools" / "skills"
    for skill_path in sorted(skills_dir.glob("*/SKILL.md")):
        name = skill_path.parent.name
        src_rel = skill_path.relative_to(root).as_posix()
        _fm, body = parse_frontmatter_body(skill_path.read_text(encoding="utf-8"))
        out[".claude/skills/%s/SKILL.md" % name] = build_skill(name, src_rel, body)

    out[".claude/agents/planner.md"] = PLANNER_AGENT
    out[".claude/agents/independent-reviewer.md"] = REVIEWER_AGENT

    instr_dir = root / "tools" / "instructions"
    for fname, rule, globs in CURSOR_RULES:
        path = instr_dir / fname
        if not path.is_file():
            continue
        src_rel = path.relative_to(root).as_posix()
        out[".cursor/rules/%s.mdc" % rule] = build_cursor_rule(rule, globs, src_rel, path.read_text(encoding="utf-8"))

    playbooks = "\n".join(
        "- `%s`" % p.relative_to(root).as_posix() for p in sorted(skills_dir.glob("*/SKILL.md"))
    )
    out[".cursor/rules/skills.mdc"] = "\n".join([
        "---",
        'description: "project-os skill playbooks: read the matching playbook before performing these operations"',
        'globs: ["**/*"]',
        "---",
        "",
        GENERATED_NOTE % "tools/skills/*/SKILL.md",
        "",
        "Before performing a project-os lifecycle operation (intake, scaffold, close-out, release, review, sync), read and follow the matching playbook:",
        "",
        playbooks,
        "",
    ])
    return out


def install_hooks(root, force=False):
    hooks_src = root / "tools" / "adapters" / "claude-code" / "hooks.json"
    if not hooks_src.is_file():
        return "hooks.json not found; skipped"
    target = root / ".claude" / "settings.json"
    hooks = json.loads(hooks_src.read_text(encoding="utf-8"))
    if not target.is_file():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(hooks_src.read_text(encoding="utf-8"), encoding="utf-8")
        return "created .claude/settings.json"
    settings = json.loads(target.read_text(encoding="utf-8"))
    if "hooks" in settings and not force:
        return "existing hooks key left alone (use --force-hooks to replace)"
    settings["hooks"] = hooks.get("hooks", {})
    target.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")
    return "merged hooks into .claude/settings.json"



def untracked_artifacts(root, artifacts):
    """Generated artifacts present on disk that git will not carry.

    The failure this catches is silent and total: the artifacts are correct
    locally, `--check` passes locally, and CI reports every one of them stale
    forever, because a fresh checkout does not contain them at all. Regenerating
    cannot fix it — the fix is always in .gitignore.

    A local check that reads the working tree cannot see the difference, which is
    exactly why it has to be asked explicitly.

    Returns [] when git is unavailable or this is not a repository: an inability
    to check is not evidence of a problem.
    """
    import subprocess

    rels = sorted(artifacts)
    if not rels:
        return []
    try:
        proc = subprocess.run(
            ["git", "-C", str(root), "ls-files", "--cached", "--"] + rels,
            capture_output=True, text=True, timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return []
    if proc.returncode != 0:
        return []
    tracked = {line.strip() for line in proc.stdout.splitlines() if line.strip()}
    return [rel for rel in rels if (root / rel).is_file() and rel not in tracked]


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate native adapter artifacts from project-os playbooks.")
    ap.add_argument("--repo-root", default=".", help="Repo root (default: cwd)")
    ap.add_argument("--check", action="store_true", help="Verify generated files are current; write nothing, exit 1 on drift")
    ap.add_argument("--install-hooks", action="store_true", help="Install the Claude Code hook set into .claude/settings.json")
    ap.add_argument("--force-hooks", action="store_true", help="With --install-hooks: replace an existing hooks key")
    args = ap.parse_args(argv)

    root = Path(args.repo_root).resolve()
    if not (root / "tools" / "skills").is_dir():
        return fail("no tools/skills under %s" % root)

    artifacts = generate(root)
    stale = []
    for rel, content in sorted(artifacts.items()):
        path = root / rel
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        if args.check:
            stale.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print("generate-adapters: wrote %s" % rel)

    if args.check:
        if stale:
            for rel in stale:
                print("generate-adapters: STALE %s" % rel)
            print("generate-adapters: %d artifact(s) out of date; run: python3 tools/scripts/generate-adapters.py" % len(stale))
            return 1
        untracked = untracked_artifacts(root, artifacts)
        if untracked:
            for rel in untracked:
                print("generate-adapters: UNTRACKED %s" % rel)
            print(
                "generate-adapters: %d artifact(s) exist here but are not tracked by git.\n"
                "  These are build outputs the repository is meant to carry (SYNCING.md: 'template-owned\n"
                "  build outputs'), so a fresh clone will not have them and CI will report every one STALE\n"
                "  however many times you regenerate. Check .gitignore — a stock '.claude/' or '.cursor/'\n"
                "  line from a language scaffold is the usual cause." % len(untracked)
            )
            return 1
        print("generate-adapters: all %d artifacts current" % len(artifacts))
        return 0

    if args.install_hooks:
        print("generate-adapters: %s" % install_hooks(root, force=args.force_hooks))
    print("generate-adapters: %d artifacts current" % len(artifacts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
